// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbfehyvhsmyvrcczkpxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZmVoeXZoc215dnJjY3prcHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTYzNDQsImV4cCI6MjA3MDc3MjM0NH0.U0svem977MHUjwcBJ_OCT0RyTlYeArJf1jgy3FTLGw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});