// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jttogvpjfeegbkpturey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0dG9ndnBqZmVlZ2JrcHR1cmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzQ1MTUsImV4cCI6MjA2ODc1MDUxNX0.Z0_12xZGStNWJH98ojGBwX2YYxT8gLghAtPQq7-7uCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});